name: Create S3 Bucket

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  create-s3-bucket:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          echo "[default]" > $HOME/.aws/credentials
          echo "aws_access_key_id=YOUR_AWS_ACCESS_KEY" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=YOUR_AWS_SECRET_KEY" >> $HOME/.aws/credentials
          chmod 600 $HOME/.aws/credentials

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg AWSCLIV2.pkg -target /

      - name: Create S3 bucket
        run: |
          aws s3api create-bucket --bucket HEMS--region GLOBAL --create-bucket-configuration LocationConstraint=YOUR_REGION
